### ISSUE TITLE
Virtualization with board view

### ISSUE THREAD

**Issue by huzaifa3115** [atlassian/pragmatic-drag-and-drop#101]
Can anyone help me implement virtualization on Kanban View,
I am using the react-virtualized package, but drag and drop is not working.

I tried to refer to the document but that is not enough and there is no example.

Many thanks for considering my request.

**Comment by alexreardon** [comment]
Might be best to move to a discussion for this rather than an issue. Here are some resources that could help you get going:

- [Our virtualisation guide](https://atlassian.design/components/pragmatic-drag-and-drop/core-package/improving-performance/virtualization)
- [An example leveraging virtualization](https://atlassian.design/components/pragmatic-drag-and-drop/examples#virtual)

If you have any specific questions please let me know.

Cheers
