### ISSUE TITLE
Tree codesandbox not working

### ISSUE THREAD

**Issue by nooblyf** [atlassian/pragmatic-drag-and-drop#118]
url: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#tree
codesandbox: https://codesandbox.io/p/sandbox/7ckkrw

![Screenshot 2024-09-15 at 20 30 08](https://github.com/user-attachments/assets/6ef0b05d-cdc1-48b8-8c1e-4a0b7fb064f2)

**Comment by codenomnom** [comment]
Any news on this one?

**Comment by marcinpl87** [comment]
If you'd like to continue work with this example, without fixing core issue, you can remove code related to `@atlaskit/modal-dialog` because this package cause this issue.

To do it you need to change only 2 files:
1. in `/pragmatic-drag-and-drop/documentation/examples/pieces/tree/tree-item.tsx` file remove lines 476 and 478
2. in `/pragmatic-drag-and-drop/documentation/examples/pieces/tree/move-dialog.tsx` replace lines 74-118 to `return null;`

you will not have move dialog, but drag&drop will work 🙂

here is codesandbox after changes mentioned above - https://codesandbox.io/p/sandbox/tree-forked-vtz3z3

**Comment by codenomnom** [comment]
Hey, thanks for spending the time figuring this out. I was hoping it's something as simple as that, but got too lazy to check it myself 😊 Appreciated!
