### ISSUE TITLE
Can't detect drag from external inside `textarea`

### ISSUE THREAD

**Issue by hellovietduc** [atlassian/pragmatic-drag-and-drop#51]
I came across this issue where if I drag a file to the webpage, the drop target events fire normally until I drag over a `textarea` _inside_ that drop target. Is this a platform issue or is there something else I should do to make this work?

**Comment by alexreardon** [comment]
Could you please create a codesandbox and I'll take a look

**Comment by hellovietduc** [comment]
@alexreardon Here it is: https://codesandbox.io/p/sandbox/optimistic-colden-xhfl4j

**Comment by alexreardon** [comment]
I am looking into this now

**Comment by alexreardon** [comment]
**🐛 Bad news**: It looks like you stumbled into a bug with our 'exiting window' logic detection.
**🎉 Good news**: This was fixed in `1.1.7` - so your example starts working if you update your version from `1.1.3` to `1.1.7`

- [your example on `1.1.6`](https://codesandbox.io/p/sandbox/textarea-bug-1-1-6-447rcf?file=%2Fpackage.json) (has bug)
- [your example on `1.1.7`](https://codesandbox.io/p/sandbox/textarea-bug-1-1-7-8xx8f5?file=%2Fpackage.json%3A11%2C48) (working)

**Comment by hellovietduc** [comment]
@alexreardon Thank you very much. Is there a public changelog where I can see what's new in each update?

**Comment by alexreardon** [comment]
https://atlassian.design/components/pragmatic-drag-and-drop/core-package/changelog/changelog

However, we do hope to publish our releases under the releases tab too

cc @ReDrUm
