### ISSUE TITLE
draggable attribute does not register in Production builds

### ISSUE THREAD

**Issue by bmark88** [atlassian/pragmatic-drag-and-drop#72]
When working with the `draggable` method provided by `@atlaskit/pragmatic-drag-and-drop/element/adapter`, the _draggable_ attribute on the HTMLElement (associated with the ref) is registered in `development`, but not a `production` build.

I can hardcode the HTMLElement _draggable_ attribute to exist and it gets registered in all environments, but because the `draggable` method is not registering the element properly, it's entirely unusable with the drag and drop features including the drop indicator.

The **app dependencies** include (but not limited to):
- NextJS 14.1.0
- React 18.2.0
- "@atlaskit/pragmatic-drag-and-drop": "=1.1.9" (This is locked to 1.1.9 because any higher version breaks the pragmatic-drag-and-drop-auto-scroll functionality in all environments)
- "@atlaskit/pragmatic-drag-and-drop-auto-scroll": "=1.1.0"
- "@atlaskit/pragmatic-drag-and-drop-hitbox": "=1.0.3"
- "@atlaskit/pragmatic-drag-and-drop-react-drop-indicator": "=1.1.1"

I've also attempted to disable React's strict mode (because I've seen other issues mentioning this could help), but this doesn't appear to work either (and actually breaks the _draggable_ HTMLElement attribute from being registered in _all_ environments).

Are there any ideas of why this might happen (or proposed solutions/workarounds)?

```
useEffect(() => {
    if (ref.current) {
      element = ref.current;

      const blockActions: HTMLCollectionOf<HTMLDivElement> = element.getElementsByClassName(
        'block-actions__grip'
      ) as HTMLCollectionOf<HTMLDivElement>;

      if (blockActions.length > 0) {
        // Initialize drag handle
        element = blockActions[0];
      } else {
        if (process.env.NODE_ENV === 'development') {
          throw Error(
            'Drag handle element not found. You must provide a drag handle with a class name including "block-actions__grip"'
          );
        }
      }
    } else {
      console.log('element in else:', element); // This does not get logged in any environment
    }
    console.log('element outside of else:', element); // This gets logged in all environments, suggesting the element is defined before attempting to register the draggable element

    return () => {
      draggable({
        element,
        onGenerateDragPreview({ nativeSetDragImage }) {
          setCustomNativeDragPreview({
            render({ container }) {
              const containerWidth = element.parentElement?.offsetWidth || '250';
              container.style.width = `${containerWidth}px`;
              // Cause a `react` re-render to create your portal synchronously
              setDragPreviewElement(container);
              // In our cleanup function: cause a `react` re-render to create remove your portal
              // Note: you can also remove the portal in `onDragStart`,
              // which is when the cleanup function is called
              return () => setDragPreviewElement(null);
            },
            nativeSetDragImage,
          });
        },
        getInitialData: ({ input, element: el }) => {
          const data = {
            blockType,
            uniqueId: sortableUniqueId,
            containingBlockId,
            relativePosition,
            blockId: id,
            parentNodeType,
          };
          return attachClosestEdge(data, {
            input,
            element: el,
            allowedEdges: ['top', 'bottom'],
          });
        },
        onDragStart: () => setDragging(true),
        onDrop: () => setDragging(false),
      });
    };
  }, []);
  ```

**Comment by alexreardon** [comment]
Hi @bmark88,

Thanks for taking an interest in this project. 

Things should be working fine with NextJS. One of our first production examples for pdnd was using NextJS.

**What I think is causing your issue**

You are registering your `draggable(...)` in the `useEffect` cleanup function, and not in the `useEffect` itself. This will work in development mode as react will [double run your effects](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development) - so the `useEffect` cleanup function is being run due to the double run. However, in production builds, when your effect is only run once, and `draggable` function is not being run, as the effect is not being double run.

In the code 

```diff
- // draggable being registered in your effect cleanup
-  return () => {
+ // registering draggable inside the effect
+ // returning the draggable cleanup function from the effect
+ return draggable({
        element,
        onGenerateDragPreview({ nativeSetDragImage }) {
          setCustomNativeDragPreview({
            render({ container }) {
              const containerWidth = element.parentElement?.offsetWidth || '250';
              container.style.width = `${containerWidth}px`;
              // Cause a `react` 
```

Let me know how you go.

To help troubleshoot your issue further, we will need an environment we can play with. [StackBlitz](https://stackblitz.com/?starters=fullstack) has an easy way to spin up a NextJS project quickly that you can share with us. 

---

> "@atlaskit/pragmatic-drag-and-drop": "=1.1.9" (This is locked to 1.1.9 because any higher version breaks the pragmatic-drag-and-drop-auto-scroll functionality in all environments)

That is concerning. We have not bumped into that issue before and we are using higher versions in production today. If you are still running into that issue, can you please create a new Github issue with a standalone reproduction example (eg on StackBlitz or Codesandbox) so we can troubleshoot for you?

Cheers!

**Comment by bmark88** [comment]
Thanks @alexreardon! Returning the draggable _as_ the cleanup function instead of within it did work.

Regarding the auto scroll functionality, I'll try to create an environment for you as soon as I have a moment. I'll link back to this issue for reference.

**Comment by alexreardon** [comment]
For clarity @bmark88:

`draggable()` returns a function (a `CleanupFn`) that can be used to restore the element to it's prior (non-draggable) state

So in the effect we are doing this:

```ts
useEffect(() => {
  const cleanupDraggable = draggable({element});

  return function cleanupEffect() {
    cleanupDraggable();
  }
}, []);
```

This is just a shortcut:

```ts
useEffect(() => {
  return draggable({element});
}, []);
